# action.yaml
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: python version
        run: |
          python3 --version
      - name: ls
        run: |
          ls -la
      - name: 0001_hello_world.py
        run: |
          python3 0001_hello_world.py
